on:
  push:
    branches:
      - main

jobs:
  whether-triggerd:
    runs-on: ubuntu-latest
    steps:
      - name: check trigger event
        run: |
          echo "## github.event_name"
          echo "${{ github.event_name }}"
          echo ""
          echo "## githb.event.action"
          echo "${{ github.event.action }}"
